// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package user

import (
	"context"

	"go-zero-k8s-test/user/rpc/userpb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddReq  = userpb.AddReq
	AddResp = userpb.AddResp

	User interface {
		Add(ctx context.Context, in *AddReq, opts ...grpc.CallOption) (*AddResp, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Add(ctx context.Context, in *AddReq, opts ...grpc.CallOption) (*AddResp, error) {
	client := userpb.NewUserClient(m.cli.Conn())
	return client.Add(ctx, in, opts...)
}
