// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"go-zero-k8s-test/user/rpc/internal/logic"
	"go-zero-k8s-test/user/rpc/internal/svc"
	"go-zero-k8s-test/user/rpc/userpb"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	userpb.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Add(ctx context.Context, in *userpb.AddReq) (*userpb.AddResp, error) {
	l := logic.NewAddLogic(ctx, s.svcCtx)
	return l.Add(in)
}
